default: &default
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  pool: <%= ENV.fetch('DB_POOL') { 25 } %>
  timeout: 5000
  template: template0

development:
  <<: *default

test:
  <<: *default

